# Generated by Django 2.1.15 on 2023-11-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('lat', models.DecimalField(decimal_places=14, default=0, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=14, default=0, max_digits=20)),
            ],
        ),
    ]
