# Generated by Django 2.1.15 on 2023-10-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanPriority',
        ),
        migrations.AddField(
            model_name='plan',
            name='priority',
            field=models.IntegerField(default=999999),
        ),
    ]
